Description: Export billing to customer bucket
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  C8DailyBillingExport:
    Type: AWS::CUR::ReportDefinition
    DependsOn:
    - C8DailyBillingBucket
    - C8DailyBillingBucketPolicy
    Properties:
      AdditionalSchemaElements: 
        - RESOURCES
      Compression: GZIP
      Format: textORcsv
      ReportName: c8-daily-report
      ReportVersioning: CREATE_NEW_REPORT
      RefreshClosedReports: False
      S3Bucket: !Ref C8DailyBillingBucket
      S3Prefix: reports/
      S3Region: us-east-1
      TimeUnit: DAILY
  C8DailyBillingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName:  !Join
        - '-'
        - - c8-export-cost
          - !Ref AWS::AccountId
      
  C8DailyBillingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - C8DailyBillingBucket
    Properties:
      Bucket:
        Ref: C8DailyBillingBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 'billingreports.amazonaws.com'
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
            Resource:
              - Fn::Join: [
                  '', [
                    'arn:aws:s3:::',
                    {
                      'Ref': 'C8DailyBillingBucket'
                    }
                  ]
                ]
          - Effect: Allow
            Principal:
              Service: 'billingreports.amazonaws.com'
            Action:
              - s3:PutObject
            Resource:
              - Fn::Join: [
                  '', [
                    'arn:aws:s3:::',
                    {
                      'Ref': 'C8DailyBillingBucket'
                    },
                    '/*'
                  ]
                ]